[tools]
node = "24.12.0"
gemini = "latest"
deno = "latest"
neovim = "latest"
fzf = "latest"
pnpm = "latest"
uv = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"

"pipx:beko-translate" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
