[tools]
node = "24.12.0"
deno = "latest"
neovim = "latest"
fzf = "latest"
pnpm = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
